### ISSUE TITLE
Move persistence_dir to defaults/ so it can be overwritten by user

### ISSUE THREAD

**Issue by TomaszUrugOlszewski** [cloudalchemy/ansible-pushgateway#50]
**What is missing?**

persistence_dir variable can't be changed

**Why do we need it?**

To keep persistence_dir on persistent disk mounted somewhere else than default directory

Pull Request - https://github.com/cloudalchemy/ansible-pushgateway/pull/49

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
