### ISSUE TITLE
pushgateway user gid is not set to pushgateway group

### ISSUE THREAD

**Issue by TomaszUrugOlszewski** [cloudalchemy/ansible-pushgateway#51]
**What happened?**

When user `pushgateway` is created, is not set to `pushgateway` group gid.

```
$ grep pushgateway /etc/passwd
pushgateway:x:996:100::/:/usr/sbin/nologin
```

Group 100 is `users`, not `pushgateway` (which is 996)

**Did you expect to see some different?**

I expect to see 996 gid (`pushgateway`)

**How to reproduce it (as minimally and precisely as possible)**:

Install pushgateway using this role

Added fix here https://github.com/cloudalchemy/ansible-pushgateway/pull/49

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
